export const names = [
  'Harry Potter',
  'Dolores Umbridge',
  'Hermione Granger',
  'Rubeus Hagrid',
  'Viktor Krum',
  'Bellatrix Lestrange',
  'Lucius Malfoy',
  'Draco Malfoy',
  'Garrick Ollivander',
  'Peter Pettigrew',
  'James Potter',
  'Lily Potter',
  'Albus Dumbledore',
  'Dobby',
  'Neville Longbottom',
  'Dudley Dursley',
  'Lord Voldemort',
  'Sirius Black',
  'Tom Riddle',
  'Minerva McGonagall',
  'Nearly Headless Nick',
  'Godric Gryffindor',
  'Salazar Slytherin',
  'Helga Hufflepuff',
  'Rowena Ravenclaw',
  'Cedric Diggory',
  'Severus Snape',
  'Ronald Weasley',
];